name: Daily WaveTour Events

permissions:
  contents: write
  
on:
  schedule:
    - cron: "0 0 * * *"  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  fetch-events:
    runs-on: ubuntu-latest
    env:
      # MySQL connection details pulled from GitHub Secrets
      DB_USER: ${{ secrets.DB_USER }}
      DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
      DB_HOST: ${{ secrets.DB_HOST }}
      DB_PORT: ${{ secrets.DB_PORT }}
      DB_DATABASE: ${{ secrets.DB_DATABASE }}
      # Optional: If your Aiven MySQL requires SSL, include the CA certificate path
      MYSQL_SSL_CA: ${{ secrets.MYSQL_SSL_CA }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run WaveTour Events Script
        run: python daily_events_check_and_update.py
